version: '3.7'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    command: mongod --dbpath /data/db
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - twhost

networks:
  twhost:
    driver: bridge

volumes:
  mongo_data:
